# Generated by Django 3.0.3 on 2020-05-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inoutform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='snippet',
            new_name='coming',
        ),
    ]
