# Generated by Django 3.0.3 on 2020-06-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inoutform', '0009_auto_20200603_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='Vehicle_id',
            field=models.CharField(choices=[('TS 10UB 8168', 'TS 10UB 8168'), ('TS 10UB 8169', 'TS 10UB 8169'), ('TS 10UB 8167', 'TS 10UB 8167'), ('TS 10UB 8173', 'TS 10UB 8173')], default='SOME STRING', max_length=255),
        ),
    ]
